### ISSUE TITLE
Most recent code pushed to github throws error

### ISSUE THREAD

**Issue by thefearlesscoder** [als-computing/splash-server#27]
When I run the most recent code pushed to github with `python run.py` I get the error:
```
Settinconfig.pg log level to 10
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    app = create_app()
  File "/home/joshua/UT Austin/splash-dev/splash-server/splash/__init__.py", line 72, in create_app
    api.add_resource(OAuthResource, "/api/tokensignin", resource_class_kwargs={'user_service': app.user_service})
AttributeError: 'Flask' object has no attribute 'user_service'
```

**Comment by dylanmcreynolds** [comment]
Are you sure you're current with https://github.com/als-computing/splash-server/blob/master/splash/__init__.py ? app.user_service is defined on line 32.
